/* tslint:disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import { Reactor } from "./reactor";

/**
 *
 * @export
 * @interface Reaction
 */
export interface Reaction {
  /**
   *
   * @type {string}
   * @memberof Reaction
   */
  type: ReactionTypeEnum;
  /**
   * Ethereum address
   * @type {string}
   * @memberof Reaction
   */
  hash: string;
  /**
   *
   * @type {Reactor}
   * @memberof Reaction
   */
  reactor: Reactor;
  /**
   *
   * @type {string}
   * @memberof Reaction
   */
  timestamp: string;
  /**
   * Ethereum address
   * @type {string}
   * @memberof Reaction
   */
  castHash: string;
}

export const ReactionTypeEnum = {
  Like: "like",
  Recast: "recast",
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type ReactionTypeEnum =
  (typeof ReactionTypeEnum)[keyof typeof ReactionTypeEnum];
