// eslint-disable-next-line eslint-comments/disable-enable-pair
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable eslint-comments/disable-enable-pair */
/* tslint:disable */
/* eslint-disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UserPfp } from "./user-pfp";

/**
 *
 * @export
 * @interface ReactionCast
 */
export interface ReactionCast {
  /**
   * User identifier (unsigned integer)
   * @type {number}
   * @memberof ReactionCast
   */
  cast_fid?: number;
  /**
   *
   * @type {string}
   * @memberof ReactionCast
   */
  cast_hash?: string;
  /**
   *
   * @type {string}
   * @memberof ReactionCast
   */
  cast_text?: string;
  /**
   *
   * @type {Array<UserPfp>}
   * @memberof ReactionCast
   */
  cast_embeds?: Array<UserPfp>;
  /**
   *
   * @type {string}
   * @memberof ReactionCast
   */
  cast_timestamp?: string;
}
