/* tslint:disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReactionWithCastMetaReaction
 */
export interface ReactionWithCastMetaReaction {
  /**
   * User identifier (unsigned integer)
   * @type {number}
   * @memberof ReactionWithCastMetaReaction
   */
  reactor_fid: number;
  /**
   *
   * @type {string}
   * @memberof ReactionWithCastMetaReaction
   */
  reaction_type: ReactionWithCastMetaReactionReactionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof ReactionWithCastMetaReaction
   */
  reaction_hash: string;
  /**
   *
   * @type {string}
   * @memberof ReactionWithCastMetaReaction
   */
  reaction_target_hash: string;
  /**
   *
   * @type {string}
   * @memberof ReactionWithCastMetaReaction
   */
  reaction_timestamp: string;
}

export const ReactionWithCastMetaReactionReactionTypeEnum = {
  Like: "like",
  Recast: "recast",
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type ReactionWithCastMetaReactionReactionTypeEnum =
  (typeof ReactionWithCastMetaReactionReactionTypeEnum)[keyof typeof ReactionWithCastMetaReactionReactionTypeEnum];
