/* tslint:disable */
/**
 * v2 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The notification type of a cast.
 * @export
 * @enum {string}
 */

export const CastNotificationType = {
  Mention: "cast-mention",
  Reply: "cast-reply",
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type CastNotificationType =
  (typeof CastNotificationType)[keyof typeof CastNotificationType];
