/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Def20
 */
export interface ApiKeyStoreKey {
  /**
   *
   * @type {string}
   * @memberof Def20
   */
  keyId: string;
  /**
   *
   * @type {string}
   * @memberof Def20
   */
  type: string;
  /**
   *
   * @type {Def3}
   * @memberof Def20
   */
  base64PublicKey: string;
  /**
   *
   * @type {Def3}
   * @memberof Def20
   */
  base64Signature: string;
  /**
   *
   * @type {Def18}
   * @memberof Def20
   */
  timestamp: number;
  /**
   *
   * @type {Def12}
   * @memberof Def20
   */
  fid?: number;
  /**
   *
   * @type {string}
   * @memberof Def20
   */
  deviceId?: string;
  /**
   *
   * @type {string}
   * @memberof Def20
   */
  deviceName?: string;
}
