/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Def23
 */
export interface ApiOpenGraphMetadata {
  /**
   *
   * @type {Def22}
   * @memberof Def23
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof Def23
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Def23
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof Def23
   */
  domain?: string;
  /**
   *
   * @type {Def22}
   * @memberof Def23
   */
  image?: string;
  /**
   *
   * @type {Def22}
   * @memberof Def23
   */
  logo?: string;
  /**
   *
   * @type {boolean}
   * @memberof Def23
   */
  useLargeImage?: boolean;
  /**
   *
   * @type {Def15}
   * @memberof Def23
   */
  strippedCastText?: string;
}
