/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetEvent } from "./AssetEvent";
import { AssetEventType } from "./AssetEventType";
/**
 *
 * @export
 * @interface Def35
 */
export interface AssetEventFeedItem {
  /**
   *
   * @type {string}
   * @memberof Def35
   */
  id: string;
  /**
   *
   * @type {Def32}
   * @memberof Def35
   */
  type: AssetEventType;
  /**
   *
   * @type {Def18}
   * @memberof Def35
   */
  latestTimestamp: number;
  /**
   *
   * @type {Array<AssetEvent>}
   * @memberof Def35
   */
  events: Array<AssetEvent>;
}
