/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from "./User";
import { AssetCollection } from "./AssetCollection";
import { AssetLastSale } from "./AssetLastSale";
import { AssetMint } from "./AssetMint";
import { AssetViewerContext } from "./AssetViewerContext";
/**
 *
 * @export
 * @interface Def30
 */
export interface Asset {
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  name: string;
  /**
   *
   * @type {Def11}
   * @memberof Def30
   */
  contractAddress: string;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  tokenId: string;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  imageUrl: string;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  externalUrl?: string;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  openSeaUrl: string;
  /**
   *
   * @type {Def2}
   * @memberof Def30
   */
  likeCount: number;
  /**
   *
   * @type {string}
   * @memberof Def30
   */
  uri: string;
  /**
   *
   * @type {AssetCollection}
   * @memberof Def30
   */
  collection: AssetCollection;
  /**
   *
   * @type {User}
   * @memberof Def30
   */
  owner?: User;
  /**
   *
   * @type {AssetLastSale}
   * @memberof Def30
   */
  lastSale?: AssetLastSale;
  /**
   *
   * @type {AssetMint}
   * @memberof Def30
   */
  mint?: AssetMint;
  /**
   *
   * @type {AssetViewerContext}
   * @memberof Def30
   */
  viewerContext?: AssetViewerContext;
}
