/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def2 } from "./def2";
import { Def41 } from "./def41";
/**
 *
 * @export
 * @interface Def42Recasts
 */
export interface CastRecasts {
  /**
   *
   * @type {Def2}
   * @memberof Def42Recasts
   */
  count: Def2;
  /**
   *
   * @type {Array<Def41>}
   * @memberof Def42Recasts
   */
  recasters?: Array<Def41>;
}
