/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from "./User";
import { CastAncestors } from "./CastAncestors";
import { CastAttachments } from "./CastAttachments";
import { CastReactions } from "./CastReactions";
import { CastRecasts } from "./CastRecasts";
import { CastViewerContext } from "./CastViewerContext";
/**
 */
export interface Cast {
  /**
   *
   * @memberof Def42
   */
  hash: string;
  /**
   *
   * @memberof Def42
   */
  threadHash: string;
  /**
   *
   * @type {Def6}
   * @memberof Def42
   */
  parentHash?: string;
  /**
   *
   * @type {User}
   * @memberof Def42
   */
  parentAuthor?: User;
  /**
   *
   * @type {User}
   * @memberof Def42
   */
  author: User;
  /**
   *
   * @type {Def15}
   * @memberof Def42
   */
  text: string;
  /**
   *
   * @type {Def18}
   * @memberof Def42
   */
  timestamp: number;
  /**
   *
   * @type {Array<User>}
   * @memberof Def42
   */
  mentions?: Array<User>;
  /**
   *
   * @type {CastAttachments}
   * @memberof Def42
   */
  attachments?: CastAttachments;
  /**
   *
   * @type {CastAncestors}
   * @memberof Def42
   */
  ancestors?: CastAncestors;
  /**
   *
   * @type {CastAncestors}
   * @memberof Def42
   */
  replies: CastAncestors;
  /**
   *
   * @type {CastReactions}
   * @memberof Def42
   */
  reactions: CastReactions;
  /**
   *
   * @type {CastRecasts}
   * @memberof Def42
   */
  recasts: CastRecasts;
  /**
   *
   * @type {CastReactions}
   * @memberof Def42
   */
  watches: CastReactions;
  /**
   *
   * @type {boolean}
   * @memberof Def42
   */
  deleted?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Def42
   */
  recast?: boolean;
  /**
   *
   * @type {CastViewerContext}
   * @memberof Def42
   */
  viewerContext?: CastViewerContext;
}
