/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def29 } from "./def29";
import { Def30 } from "./def30";
/**
 *
 * @export
 * @interface Def31
 */
export interface Def31 {
  /**
   *
   * @type {Def29}
   * @memberof Def31
   */
  collection: Def29;
  /**
   *
   * @type {Array<Def30>}
   * @memberof Def31
   */
  assets: Array<Def30>;
}
