/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def18 } from "./def18";
import { User } from "./User";
import { Def30 } from "./def30";
import { Def32 } from "./def32";
import { Def33 } from "./def33";
/**
 *
 * @export
 * @interface Def34
 */
export interface Def34 {
  /**
   *
   * @type {string}
   * @memberof Def34
   */
  id: string;
  /**
   *
   * @type {Def18}
   * @memberof Def34
   */
  timestamp: Def18;
  /**
   *
   * @type {Def32}
   * @memberof Def34
   */
  type: Def32;
  /**
   *
   * @type {Def33}
   * @memberof Def34
   */
  verb: Def33;
  /**
   *
   * @type {Def30}
   * @memberof Def34
   */
  asset: Def30;
  /**
   *
   * @type {User}
   * @memberof Def34
   */
  user: User;
}
