/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def18 } from "./def18";
import { Def32 } from "./def32";
import { Def34 } from "./def34";
/**
 *
 * @export
 * @interface Def35
 */
export interface Def35 {
  /**
   *
   * @type {string}
   * @memberof Def35
   */
  id: string;
  /**
   *
   * @type {Def32}
   * @memberof Def35
   */
  type: Def32;
  /**
   *
   * @type {Def18}
   * @memberof Def35
   */
  latestTimestamp: Def18;
  /**
   *
   * @type {Array<Def34>}
   * @memberof Def35
   */
  events: Array<Def34>;
}
