/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def11 } from "./def11";
import { Def18 } from "./def18";
import { User } from "./User";
import { Def6 } from "./def6";
import { Def8 } from "./def8";
/**
 *
 * @export
 * @interface Def37
 */
export interface Def37 {
  /**
   *
   * @type {Def8}
   * @memberof Def37
   */
  type: Def8;
  /**
   *
   * @type {Def11}
   * @memberof Def37
   */
  hash: Def11;
  /**
   *
   * @type {User}
   * @memberof Def37
   */
  reactor: User;
  /**
   *
   * @type {Def18}
   * @memberof Def37
   */
  timestamp: Def18;
  /**
   *
   * @type {Def6}
   * @memberof Def37
   */
  castHash: Def6;
}
