/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def12 } from "./def12";
import { Def18 } from "./def18";
/**
 *
 * @export
 * @interface Def45
 */
export interface Def45 {
  /**
   *
   * @type {Array<Def12>}
   * @memberof Def45
   */
  participantFids: Array<Def12>;
  /**
   *
   * @type {Def18}
   * @memberof Def45
   */
  lastDirectCastTimestamp: Def18;
}
