/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def2 } from "./def2";
import { Def29 } from "./def29";
import { Def34 } from "./def34";
/**
 *
 * @export
 * @interface Def40
 */
export interface Def40 {
  /**
   *
   * @type {Def29}
   * @memberof Def40
   */
  collection: Def29;
  /**
   *
   * @type {Def34}
   * @memberof Def40
   */
  firstEvent: Def34;
  /**
   *
   * @type {Def2}
   * @memberof Def40
   */
  recentUniqueUsersCount: Def2;
}
