/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def18 } from "./def18";
import { User } from "./User";
import { Cast } from "./Cast";
import { Def6 } from "./def6";
/**
 *
 * @export
 * @interface Def61
 */
export interface Def61 {
  /**
   *
   * @type {Def6}
   * @memberof Def61
   */
  id: Def6;
  /**
   *
   * @type {Def18}
   * @memberof Def61
   */
  timestamp: Def18;
  /**
   *
   * @type {Cast}
   * @memberof Def61
   */
  cast: Cast;
  /**
   *
   * @type {Array<Cast>}
   * @memberof Def61
   */
  replies?: Array<Cast>;
  /**
   *
   * @type {Array<User>}
   * @memberof Def61
   */
  otherParticipants: Array<User>;
}
