/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from "./User";
import { DirectCastViewerContext } from "./DirectCastViewerContext";
/**
 *
 * @export
 * @interface Def43
 */
export interface DirectCast {
  /**
   *
   * @type {User}
   * @memberof Def43
   */
  sender: User;
  /**
   *
   * @type {string}
   * @memberof Def43
   */
  text: string;
  /**
   *
   * @type {Def18}
   * @memberof Def43
   */
  timestamp: number;
  /**
   *
   * @type {DirectCastViewerContext}
   * @memberof Def43
   */
  viewerContext?: DirectCastViewerContext;
}
