/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20016Result } from "./inline-response20016-result";
import { PaginationInfo } from "./PaginationInfo";
/**
 *
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 {
  /**
   *
   * @type {InlineResponse20016Result}
   * @memberof InlineResponse20016
   */
  result: InlineResponse20016Result;
  /**
   *
   * @type {InlineResponse2001Next}
   * @memberof InlineResponse20016
   */
  next?: PaginationInfo;
}
