/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20011Result } from "./inline-response20011-result";
import { PaginationInfo } from "./PaginationInfo";
/**
 *
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
  /**
   *
   * @type {InlineResponse20011Result}
   * @memberof InlineResponse20011
   */
  result: InlineResponse20011Result;
  /**
   *
   * @type {InlineResponse2001Next}
   * @memberof InlineResponse20011
   */
  next?: PaginationInfo;
}
