/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2006Result } from "./inline-response2006-result";
import { PaginationInfo } from "./PaginationInfo";
/**
 *
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
  /**
   *
   * @type {InlineResponse2006Result}
   * @memberof InlineResponse2006
   */
  result: InlineResponse2006Result;
  /**
   *
   * @type {InlineResponse2001Next}
   * @memberof InlineResponse2006
   */
  next?: PaginationInfo;
}
