/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2001Result } from "./inline-response2001-result";
import { PaginationInfo } from "./PaginationInfo";
/**
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
  /**
   *
   * @type {InlineResponse2001Result}
   * @memberof InlineResponse2001
   */
  result: InlineResponse2001Result;
  /**
   *
   * @type {InlineResponse2001Next}
   * @memberof InlineResponse2001
   */
  next?: PaginationInfo;
}
