/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CastReaction } from "./CastReaction";
import { Cast } from "./Cast";
/**
 *
 * @export
 * @interface Def47Content
 */
export interface NotificationCastReactionContent {
  /**
   *
   * @type {Cast}
   * @memberof Def47Content
   */
  cast: Cast;
  /**
   *
   * @type {CastReaction}
   * @memberof Def47Content
   */
  reaction: CastReaction;
}
