/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from "./User";
import { NotificationWatchedCastReplyContent } from "./NotificationWatchedCastReplyContent";
/**
 *
 * @export
 * @interface Def52
 */
export interface NotificationWatchedCastReply {
  /**
   *
   * @type {string}
   * @memberof Def52
   */
  type: "watched-cast-reply";
  /**
   *
   * @type {string}
   * @memberof Def52
   */
  id: string;
  /**
   *
   * @type {Def18}
   * @memberof Def52
   */
  timestamp: number;
  /**
   *
   * @type {User}
   * @memberof Def52
   */
  actor: User;
  /**
   *
   * @type {NotificationWatchedCastReplyContent}
   * @memberof Def52
   */
  content: NotificationWatchedCastReplyContent;
}
