/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PFP } from "./PFP";
import { UserProfile } from "./UserProfile";
import { UserViewerContext } from "./UserViewerContext";
/**
 *
 * @export
 * @interface Def27
 */
export interface User {
  fid: number;
  username?: string;
  displayName: string;
  registeredAt?: number;
  /**
   *
   * @type {PFP}
   * @memberof Def27
   */
  pfp?: PFP;
  /**
   *
   * @type {UserProfile}
   * @memberof Def27
   */
  profile?: UserProfile;
  followerCount: number;
  followingCount: number;
  /**
   *
   * @type {Def13}
   * @memberof Def27
   */
  referrerUsername?: string;
  /**
   *
   * @type {UserViewerContext}
   * @memberof Def27
   */
  viewerContext?: UserViewerContext;
}
