/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2authParams } from "./v2auth-params";
/**
 *
 * @export
 * @interface V2AuthBody
 */
export interface V2AuthBody {
  /**
   *
   * @type {string}
   * @memberof V2AuthBody
   */
  method: V2AuthBodyMethodEnum;
  /**
   *
   * @type {V2authParams}
   * @memberof V2AuthBody
   */
  params: V2authParams;
}

/**
 * @export
 * @enum {string}
 */
export enum V2AuthBodyMethodEnum {
  GenerateToken = "generateToken",
}
