/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2castsParent } from "./v2casts-parent";
/**
 *
 * @export
 * @interface V2CastsBody
 */
export interface V2CastsBody {
  /**
   *
   * @type {string}
   * @memberof V2CastsBody
   */
  text: string;
  /**
   *
   * @type {V2castsParent}
   * @memberof V2CastsBody
   */
  parent?: V2castsParent;
}
