/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface V2WatchedCastsBody
 */
export interface V2WatchedCastsBody {
  /**
   *
   * @type {Def12}
   * @memberof V2WatchedCastsBody
   */
  castFid: number;
  /**
   *
   * @type {Def6}
   * @memberof V2WatchedCastsBody
   */
  castHash: string;
}
