/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def2 } from "./def2";
/**
 *
 * @export
 * @interface V2authParams
 */
export interface V2authParams {
  /**
   *
   * @type {Def2}
   * @memberof V2authParams
   */
  timestamp: Def2;
  /**
   *
   * @type {Def2}
   * @memberof V2authParams
   */
  expiresAt?: Def2;
}
