/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Def12 } from "./def12";
import { Def6 } from "./def6";
/**
 *
 * @export
 * @interface V2castsParent
 */
export interface V2castsParent {
  /**
   *
   * @type {Def12}
   * @memberof V2castsParent
   */
  fid: Def12;
  /**
   *
   * @type {Def6}
   * @memberof V2castsParent
   */
  hash: Def6;
}
