/* tslint:disable */
/* eslint-disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CastsResponseResult } from "./casts-response-result";

/**
 *
 * @export
 * @interface CastsResponse
 */
export interface CastsResponse {
  /**
   *
   * @type {CastsResponseResult}
   * @memberof CastsResponse
   */
  result: CastsResponseResult;
}
