/* tslint:disable */
/* eslint-disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Cast } from "./cast";
// May contain unused imports in some cases
// @ts-ignore
import { CastAuthor } from "./cast-author";
// May contain unused imports in some cases
// @ts-ignore
import { CastParentAuthor } from "./cast-parent-author";
// May contain unused imports in some cases
// @ts-ignore
import { CastType } from "./cast-type";
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsAllOf } from "./cast-with-interactions-all-of";
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsReactionsOrRecasts } from "./cast-with-interactions-reactions-or-recasts";
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsReplies } from "./cast-with-interactions-replies";
// May contain unused imports in some cases
// @ts-ignore
import { EmbedUrl } from "./embed-url";
// May contain unused imports in some cases
// @ts-ignore
import { ViewerContext } from "./viewer-context";

/**
 * @type CastWithInteractions
 * @export
 */
export type CastWithInteractions = Cast & CastWithInteractionsAllOf;
