/* tslint:disable */
/* eslint-disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The reaction type of a cast.   - like: Cast is being liked by a user.   - recast: Cast is being recasted by a user.
 * @export
 * @enum {string}
 */

export enum ReactionType {
  Like = "like",
  Recast = "recast",
}
