/* tslint:disable */
/* eslint-disable */
/**
 * v1 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ViewerContext
 */
export interface ViewerContext {
  /**
   *
   * @type {boolean}
   * @memberof ViewerContext
   */
  following: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ViewerContext
   */
  followedBy: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ViewerContext
   */
  liked?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ViewerContext
   */
  recasted?: boolean;
}
