/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, {
  AxiosResponse,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
import { InlineResponse2003 } from "../models";
import { InlineResponse2004 } from "../models";
import { V2AuthBody } from "../models";
import { V2AuthBody1 } from "../models";
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Revokes an authentication token.
     * @param {string} authorization
     * @param {V2AuthBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2AuthDelete: async (
      authorization: string,
      body?: V2AuthBody1,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'authorization' is not null or undefined
      if (authorization === null || authorization === undefined) {
        throw new RequiredError(
          "authorization",
          "Required parameter authorization was null or undefined when calling v2AuthDelete."
        );
      }
      const localVarPath = `/v2/auth`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (authorization !== undefined && authorization !== null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers!["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * Generates an authentication token.
     * @param {V2AuthBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2AuthPut: async (
      body?: V2AuthBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/auth`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers!["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Revokes an authentication token.
     * @param {string} authorization
     * @param {V2AuthBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2AuthDelete(
      authorization: string,
      body?: V2AuthBody1,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2004>>
    > {
      const localVarAxiosArgs = await AuthApiAxiosParamCreator(
        configuration
      ).v2AuthDelete(authorization, body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Generates an authentication token.
     * @param {V2AuthBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2AuthPut(
      body?: V2AuthBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2003>>
    > {
      const localVarAxiosArgs = await AuthApiAxiosParamCreator(
        configuration
      ).v2AuthPut(body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * Revokes an authentication token.
     * @param {string} authorization
     * @param {V2AuthBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2AuthDelete(
      authorization: string,
      body?: V2AuthBody1,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2004>> {
      return AuthApiFp(configuration)
        .v2AuthDelete(authorization, body, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Generates an authentication token.
     * @param {V2AuthBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2AuthPut(
      body?: V2AuthBody,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2003>> {
      return AuthApiFp(configuration)
        .v2AuthPut(body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
  /**
   * Revokes an authentication token.
   * @param {string} authorization
   * @param {V2AuthBody1} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public async v2AuthDelete(
    authorization: string,
    body?: V2AuthBody1,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2004>> {
    return AuthApiFp(this.configuration)
      .v2AuthDelete(authorization, body, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * Generates an authentication token.
   * @param {V2AuthBody} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public async v2AuthPut(
    body?: V2AuthBody,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2003>> {
    return AuthApiFp(this.configuration)
      .v2AuthPut(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
