/* tslint:disable */
/* eslint-disable */
/**
 * Merkle API
 * API documentation for all publicly exposed APIs provided by Merkle Manufactory, Inc for Farcaster V2.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, {
  AxiosResponse,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
import { InlineResponse2004 } from "../models";
import { InlineResponse2009 } from "../models";
import { V2FollowsBody } from "../models";
import { V2FollowsBody1 } from "../models";
/**
 * FollowsApi - axios parameter creator
 * @export
 */
export const FollowsApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Get all users that follow the specified user.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2FollowersGet: async (
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'fid' is not null or undefined
      if (fid === null || fid === undefined) {
        throw new RequiredError(
          "fid",
          "Required parameter fid was null or undefined when calling v2FollowersGet."
        );
      }
      // verify required parameter 'limit' is not null or undefined
      if (limit === null || limit === undefined) {
        throw new RequiredError(
          "limit",
          "Required parameter limit was null or undefined when calling v2FollowersGet."
        );
      }
      // verify required parameter 'authorization' is not null or undefined
      if (authorization === null || authorization === undefined) {
        throw new RequiredError(
          "authorization",
          "Required parameter authorization was null or undefined when calling v2FollowersGet."
        );
      }
      const localVarPath = `/v2/followers`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (cursor !== undefined) {
        localVarQueryParameter["cursor"] = cursor;
      }

      if (fid !== undefined) {
        localVarQueryParameter["fid"] = fid;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (authorization !== undefined && authorization !== null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * Get all users the specified user is following.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2FollowingGet: async (
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'fid' is not null or undefined
      if (fid === null || fid === undefined) {
        throw new RequiredError(
          "fid",
          "Required parameter fid was null or undefined when calling v2FollowingGet."
        );
      }
      // verify required parameter 'limit' is not null or undefined
      if (limit === null || limit === undefined) {
        throw new RequiredError(
          "limit",
          "Required parameter limit was null or undefined when calling v2FollowingGet."
        );
      }
      // verify required parameter 'authorization' is not null or undefined
      if (authorization === null || authorization === undefined) {
        throw new RequiredError(
          "authorization",
          "Required parameter authorization was null or undefined when calling v2FollowingGet."
        );
      }
      const localVarPath = `/v2/following`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (fid !== undefined) {
        localVarQueryParameter["fid"] = fid;
      }

      if (cursor !== undefined) {
        localVarQueryParameter["cursor"] = cursor;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (authorization !== undefined && authorization !== null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * Unfollow a user.
     * @param {string} authorization
     * @param {V2FollowsBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2FollowsDelete: async (
      authorization: string,
      body?: V2FollowsBody1,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'authorization' is not null or undefined
      if (authorization === null || authorization === undefined) {
        throw new RequiredError(
          "authorization",
          "Required parameter authorization was null or undefined when calling v2FollowsDelete."
        );
      }
      const localVarPath = `/v2/follows`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (authorization !== undefined && authorization !== null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers!["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * Follow a user.
     * @param {string} authorization
     * @param {V2FollowsBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2FollowsPut: async (
      authorization: string,
      body?: V2FollowsBody,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'authorization' is not null or undefined
      if (authorization === null || authorization === undefined) {
        throw new RequiredError(
          "authorization",
          "Required parameter authorization was null or undefined when calling v2FollowsPut."
        );
      }
      const localVarPath = `/v2/follows`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (authorization !== undefined && authorization !== null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers!["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * FollowsApi - functional programming interface
 * @export
 */
export const FollowsApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Get all users that follow the specified user.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowersGet(
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2009>>
    > {
      const localVarAxiosArgs = await FollowsApiAxiosParamCreator(
        configuration
      ).v2FollowersGet(fid, limit, authorization, cursor, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Get all users the specified user is following.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowingGet(
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2009>>
    > {
      const localVarAxiosArgs = await FollowsApiAxiosParamCreator(
        configuration
      ).v2FollowingGet(fid, limit, authorization, cursor, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Unfollow a user.
     * @param {string} authorization
     * @param {V2FollowsBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowsDelete(
      authorization: string,
      body?: V2FollowsBody1,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2004>>
    > {
      const localVarAxiosArgs = await FollowsApiAxiosParamCreator(
        configuration
      ).v2FollowsDelete(authorization, body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Follow a user.
     * @param {string} authorization
     * @param {V2FollowsBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowsPut(
      authorization: string,
      body?: V2FollowsBody,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => Promise<AxiosResponse<InlineResponse2004>>
    > {
      const localVarAxiosArgs = await FollowsApiAxiosParamCreator(
        configuration
      ).v2FollowsPut(authorization, body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * FollowsApi - factory interface
 * @export
 */
export const FollowsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * Get all users that follow the specified user.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowersGet(
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2009>> {
      return FollowsApiFp(configuration)
        .v2FollowersGet(fid, limit, authorization, cursor, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get all users the specified user is following.
     * @param {number} limit
     * @param {string} authorization
     * @param {string} [cursor]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowingGet(
      fid: number,
      limit: number,
      authorization: string,
      cursor?: string,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2009>> {
      return FollowsApiFp(configuration)
        .v2FollowingGet(fid, limit, authorization, cursor, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Unfollow a user.
     * @param {string} authorization
     * @param {V2FollowsBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowsDelete(
      authorization: string,
      body?: V2FollowsBody1,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2004>> {
      return FollowsApiFp(configuration)
        .v2FollowsDelete(authorization, body, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Follow a user.
     * @param {string} authorization
     * @param {V2FollowsBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2FollowsPut(
      authorization: string,
      body?: V2FollowsBody,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<InlineResponse2004>> {
      return FollowsApiFp(configuration)
        .v2FollowsPut(authorization, body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * FollowsApi - object-oriented interface
 * @export
 * @class FollowsApi
 * @extends {BaseAPI}
 */
export class FollowsApi extends BaseAPI {
  /**
   * Get all users that follow the specified user.
   * @param {number} limit
   * @param {string} authorization
   * @param {string} [cursor]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FollowsApi
   */
  public async v2FollowersGet(
    fid: number,
    limit: number,
    authorization: string,
    cursor?: string,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2009>> {
    return FollowsApiFp(this.configuration)
      .v2FollowersGet(fid, limit, authorization, cursor, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * Get all users the specified user is following.
   * @param {number} limit
   * @param {string} authorization
   * @param {string} [cursor]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FollowsApi
   */
  public async v2FollowingGet(
    fid: number,
    limit: number,
    authorization: string,
    cursor?: string,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2009>> {
    return FollowsApiFp(this.configuration)
      .v2FollowingGet(fid, limit, authorization, cursor, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * Unfollow a user.
   * @param {string} authorization
   * @param {V2FollowsBody1} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FollowsApi
   */
  public async v2FollowsDelete(
    authorization: string,
    body?: V2FollowsBody1,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2004>> {
    return FollowsApiFp(this.configuration)
      .v2FollowsDelete(authorization, body, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * Follow a user.
   * @param {string} authorization
   * @param {V2FollowsBody} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FollowsApi
   */
  public async v2FollowsPut(
    authorization: string,
    body?: V2FollowsBody,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<InlineResponse2004>> {
    return FollowsApiFp(this.configuration)
      .v2FollowsPut(authorization, body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
