/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FidsRequest
 */
export interface FidsRequest {
    /**
     * 
     * @type {number}
     * @memberof FidsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof FidsRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FidsRequest
     */
    'reverse'?: boolean;
}

