/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdRegisterEventBody } from './id-register-event-body';
// May contain unused imports in some cases
// @ts-ignore
import { OnChainEventType } from './on-chain-event-type';
// May contain unused imports in some cases
// @ts-ignore
import { SignerEventBody } from './signer-event-body';
// May contain unused imports in some cases
// @ts-ignore
import { SignerMigratedEventBody } from './signer-migrated-event-body';
// May contain unused imports in some cases
// @ts-ignore
import { StorageRentEventBody } from './storage-rent-event-body';

/**
 * 
 * @export
 * @interface OnChainEvent
 */
export interface OnChainEvent {
    /**
     * 
     * @type {OnChainEventType}
     * @memberof OnChainEvent
     */
    'type'?: OnChainEventType;
    /**
     * 
     * @type {number}
     * @memberof OnChainEvent
     */
    'chainId'?: number;
    /**
     * 
     * @type {number}
     * @memberof OnChainEvent
     */
    'blockNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof OnChainEvent
     */
    'blockHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnChainEvent
     */
    'blockTimestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnChainEvent
     */
    'transactionHash'?: string;
    /**
     * 
     * @type {number}
     * @memberof OnChainEvent
     */
    'logIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof OnChainEvent
     */
    'fid'?: string;
    /**
     * 
     * @type {SignerEventBody}
     * @memberof OnChainEvent
     */
    'signerEventBody'?: SignerEventBody;
    /**
     * 
     * @type {SignerMigratedEventBody}
     * @memberof OnChainEvent
     */
    'signerMigratedEventBody'?: SignerMigratedEventBody;
    /**
     * 
     * @type {IdRegisterEventBody}
     * @memberof OnChainEvent
     */
    'idRegisterEventBody'?: IdRegisterEventBody;
    /**
     * 
     * @type {StorageRentEventBody}
     * @memberof OnChainEvent
     */
    'storageRentEventBody'?: StorageRentEventBody;
    /**
     * 
     * @type {number}
     * @memberof OnChainEvent
     */
    'txIndex'?: number;
}



