/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OnChainEventType } from './on-chain-event-type';

/**
 * 
 * @export
 * @interface OnChainEventRequest
 */
export interface OnChainEventRequest {
    /**
     * 
     * @type {string}
     * @memberof OnChainEventRequest
     */
    'fid'?: string;
    /**
     * 
     * @type {OnChainEventType}
     * @memberof OnChainEventRequest
     */
    'eventType'?: OnChainEventType;
    /**
     * 
     * @type {number}
     * @memberof OnChainEventRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof OnChainEventRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OnChainEventRequest
     */
    'reverse'?: boolean;
}



