/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const SignerEventType = {
    None: 'SIGNER_EVENT_TYPE_NONE',
    Add: 'SIGNER_EVENT_TYPE_ADD',
    Remove: 'SIGNER_EVENT_TYPE_REMOVE',
    AdminReset: 'SIGNER_EVENT_TYPE_ADMIN_RESET'
} as const;

export type SignerEventType = typeof SignerEventType[keyof typeof SignerEventType];



