/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - FARCASTER_NETWORK_MAINNET: Public primary network  - FARCASTER_NETWORK_TESTNET: Public test network  - FARCASTER_NETWORK_DEVNET: Private test network
 * @export
 * @enum {string}
 */

export enum FarcasterNetwork {
    None = 'FARCASTER_NETWORK_NONE',
    Mainnet = 'FARCASTER_NETWORK_MAINNET',
    Testnet = 'FARCASTER_NETWORK_TESTNET',
    Devnet = 'FARCASTER_NETWORK_DEVNET'
}



