/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GetUserDataByFid200ResponseOneOf } from "./get-user-data-by-fid200-response-one-of";
// May contain unused imports in some cases
// @ts-ignore
import { HashScheme } from "./hash-scheme";
// May contain unused imports in some cases
// @ts-ignore
import { MessageDataUserDataAdd } from "./message-data-user-data-add";
// May contain unused imports in some cases
// @ts-ignore
import { SignatureScheme } from "./signature-scheme";
// May contain unused imports in some cases
// @ts-ignore
import { UserDataAdd } from "./user-data-add";

/**
 * @type GetUserDataByFid200Response
 * @export
 */
export type GetUserDataByFid200Response =
  | GetUserDataByFid200ResponseOneOf
  | UserDataAdd;
