/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - HASH_SCHEME_BLAKE3: Default scheme for hashing MessageData
 * @export
 * @enum {string}
 */

export enum HashScheme {
    None = 'HASH_SCHEME_NONE',
    Blake3 = 'HASH_SCHEME_BLAKE3'
}



