/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ListOnChainSignersByFid200ResponseOneOf } from './list-on-chain-signers-by-fid200-response-one-of';
// May contain unused imports in some cases
// @ts-ignore
import { OnChainEventSigner } from './on-chain-event-signer';
// May contain unused imports in some cases
// @ts-ignore
import { SignerEventBody } from './signer-event-body';

/**
 * @type ListOnChainSignersByFid200Response
 * @export
 */
export type ListOnChainSignersByFid200Response = ListOnChainSignersByFid200ResponseOneOf | OnChainEventSigner;


