/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Message } from "./message";
// May contain unused imports in some cases
// @ts-ignore
import { UserNameProof } from "./user-name-proof";

/**
 *
 * @export
 * @interface MergeUserNameProofBody
 */
export interface MergeUserNameProofBody {
  /**
   *
   * @type {UserNameProof}
   * @memberof MergeUserNameProofBody
   */
  usernameProof?: UserNameProof;
  /**
   *
   * @type {UserNameProof}
   * @memberof MergeUserNameProofBody
   */
  deletedUsernameProof?: UserNameProof;
  /**
   *
   * @type {Message}
   * @memberof MergeUserNameProofBody
   */
  usernameProofMessage?: Message;
  /**
   *
   * @type {Message}
   * @memberof MergeUserNameProofBody
   */
  deletedUsernameProofMessage?: Message;
}
