/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * - MESSAGE_TYPE_CAST_ADD: Add a new Cast  - MESSAGE_TYPE_CAST_REMOVE: Remove an existing Cast  - MESSAGE_TYPE_REACTION_ADD: Add a Reaction to a Cast  - MESSAGE_TYPE_REACTION_REMOVE: Remove a Reaction from a Cast  - MESSAGE_TYPE_LINK_ADD: Add a new Link  - MESSAGE_TYPE_LINK_REMOVE: Remove an existing Link  - MESSAGE_TYPE_VERIFICATION_ADD_ETH_ADDRESS: Add a Verification of an Ethereum Address  - MESSAGE_TYPE_VERIFICATION_REMOVE: Remove a Verification  - MESSAGE_TYPE_USER_DATA_ADD: Deprecated  MESSAGE_TYPE_SIGNER_ADD = 9; // Add a new Ed25519 key pair that signs messages for a user  MESSAGE_TYPE_SIGNER_REMOVE = 10; // Remove an Ed25519 key pair that signs messages for a user  Add metadata about a user  - MESSAGE_TYPE_USERNAME_PROOF: Add or replace a username proof
 * @export
 * @enum {string}
 */

export enum MessageType {
  CastAdd = "MESSAGE_TYPE_CAST_ADD",
  CastRemove = "MESSAGE_TYPE_CAST_REMOVE",
  ReactionAdd = "MESSAGE_TYPE_REACTION_ADD",
  ReactionRemove = "MESSAGE_TYPE_REACTION_REMOVE",
  LinkAdd = "MESSAGE_TYPE_LINK_ADD",
  LinkRemove = "MESSAGE_TYPE_LINK_REMOVE",
  VerificationAddEthAddress = "MESSAGE_TYPE_VERIFICATION_ADD_ETH_ADDRESS",
  VerificationRemove = "MESSAGE_TYPE_VERIFICATION_REMOVE",
  UserDataAdd = "MESSAGE_TYPE_USER_DATA_ADD",
  UsernameProof = "MESSAGE_TYPE_USERNAME_PROOF",
}
