/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FarcasterNetwork } from './farcaster-network';
// May contain unused imports in some cases
// @ts-ignore
import { LinkBody } from './link-body';
// May contain unused imports in some cases
// @ts-ignore
import { MessageDataCommon } from './message-data-common';
// May contain unused imports in some cases
// @ts-ignore
import { MessageDataLinkAllOf } from './message-data-link-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { MessageType } from './message-type';

/**
 * @type MessageDataLink
 * @export
 */
export type MessageDataLink = MessageDataCommon & MessageDataLinkAllOf;


