/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { VerificationRemoveBody } from "./verification-remove-body";

/**
 *
 * @export
 * @interface MessageDataVerificationRemoveAllOf
 */
export interface MessageDataVerificationRemoveAllOf {
  /**
   *
   * @type {VerificationRemoveBody}
   * @memberof MessageDataVerificationRemoveAllOf
   */
  verificationRemoveBody: VerificationRemoveBody;
}
