/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DataLinkAdd|MessageDataCastAdd|MessageDataCastRemove|MessageDataReactionAdd } from './data-link-add|message-data-cast-add|message-data-cast-remove|message-data-reaction-add';

/**
 * 
 * @export
 * @interface MessageAllOf
 */
export interface MessageAllOf {
    /**
     * 
     * @type {MessageDataCastAdd | MessageDataCastRemove | MessageDataLinkAdd | MessageDataReactionAdd}
     * @memberof MessageAllOf
     */
    'data': MessageDataCastAdd | MessageDataCastRemove | MessageDataLinkAdd | MessageDataReactionAdd;
}

