/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - REACTION_TYPE_LIKE: Like the target cast  - REACTION_TYPE_RECAST: Share target cast to the user\'s audience
 * @export
 * @enum {string}
 */

export enum ReactionType {
    Like = 'REACTION_TYPE_LIKE',
    Recast = 'REACTION_TYPE_RECAST'
}



