/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncStatus
 */
export interface SyncStatus {
    /**
     * 
     * @type {string}
     * @memberof SyncStatus
     */
    'peerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncStatus
     */
    'inSync'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncStatus
     */
    'shouldSync'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SyncStatus
     */
    'divergencePrefix'?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncStatus
     */
    'divergenceSecondsAgo'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncStatus
     */
    'theirMessages'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncStatus
     */
    'ourMessages'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncStatus
     */
    'lastBadSync'?: number;
}

