/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SyncStatus } from './sync-status';

/**
 * 
 * @export
 * @interface SyncStatusResponse
 */
export interface SyncStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SyncStatusResponse
     */
    'isSyncing'?: boolean;
    /**
     * 
     * @type {Array<SyncStatus>}
     * @memberof SyncStatusResponse
     */
    'syncStatus'?: Array<SyncStatus>;
    /**
     * 
     * @type {boolean}
     * @memberof SyncStatusResponse
     */
    'engineStarted'?: boolean;
}

