/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TrieNodeMetadataResponse
 */
export interface TrieNodeMetadataResponse {
    /**
     * 
     * @type {string}
     * @memberof TrieNodeMetadataResponse
     */
    'prefix'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrieNodeMetadataResponse
     */
    'numMessages'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrieNodeMetadataResponse
     */
    'hash'?: string;
    /**
     * 
     * @type {Array<TrieNodeMetadataResponse>}
     * @memberof TrieNodeMetadataResponse
     */
    'children'?: Array<TrieNodeMetadataResponse>;
}

