/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RegistryV2 } from "./RegistryV2";

export { RegistryV2__factory } from "./factories/RegistryV2__factory";
