/* tslint:disable */
/**
 * v2 Farcaster
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CastWithInteractions } from "./cast-with-interactions";
import { NextCursor } from "./next-cursor";

/**
 *
 * @export
 * @interface FeedResponse
 */
export interface FeedResponse {
  /**
   *
   * @type {CastWithInteractions[]}
   * @memberof FeedResponse
   */
  casts: CastWithInteractions[];
  /**
   *
   * @type {NextCursor}
   * @memberof FeedResponse
   */
  next: NextCursor;
}
