#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn type:check

# tests are too flakey to enforce this now on every commit
# yarn test

yarn format:check
yarn lint:check
yarn spell:check
yarn docs; git add README.md docs
